### ISSUE TITLE
Identifier name is too long

### ISSUE THREAD

**Issue by ermilov** [flamarkt/taxonomies#10]
flarum.ERROR: PDOException: SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'flarum_flamarkt_discussion_taxonomy_term_discussion_id_term_id_primary' is too long in /flarum/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117

**Comment by clarkwinkelmann** [comment]
This is caused by the length of the database table prefix added to the automatically generated index names.

I am currently not planning to address this issue in the extension. I hope Flarum introduces either a proper error message or a dynamically adapted index name based on the database prefix length.

At the moment the only solution is to use a shorter database table prefix. I think I answered a previous discussion about this issue where I calculated the maximum compatible prefix length (it might be something like just 3 or 4 chars max), it might have been an answer in the discussion on the Flarum community. I recommend using a dedicated database and no prefix.

Unfortunately you might have corrupted your database by enabling the extension on a forum with a prefix too long and there's no built-in way to change the prefix on an existing Flarum installation. You will have to perform some manual changes using a database management tool or SQL queries. You might need to manually delete some of the tables and columns already added by this extension in order to re-try the installation afterwards.

This is unfortunately not a problem specific to this extension, it can happen with any extension when long table prefixes are combined with long table and column names. It just so happens that I used some pretty long table and column names in this extension.

If you need help restoring your database to a working state or to prepare for a re-try, you might be able to find some people to help on the Flarum community or Discord server.
