### ISSUE TITLE
Thousands of errors/requests when filtering a taxonomy with the name "Tags"

### ISSUE THREAD

**Issue by iamdarkle** [flamarkt/taxonomies#3]
I have found a rather curious bug, I was receiving tens of thousands of requests without knowing exactly why. I think I've found the cause, it turns out that I named a taxonomy "Tags" and when users filter any of the terms in that taxonomy it causes thousands of errors in a matter of seconds. Simply by changing the name to Tags1 all this stops happening so I would say that this is the direct cause.

**Comment by clarkwinkelmann** [comment]
ah yes that's a warning that was present in the old README but I have not copied it over. There will be official documentation pages for each Flamarkt extension on the Flamarkt website soon... once I get the website actually ready and online.

The name of the taxonomy itself shouldn't matter, only the slug.

Link to the old README https://github.com/FriendsOfFlarum/taxonomies

> Slugs are used for search queries and as part of some URLs. You should avoid reserved terms in Taxonomy slugs, like `tag`, `tags`, `page`, `limit`, `include`, `sort`, `q` as these might conflict with Flarum or other extensions.

I didn't want to flat out ban those terms because depending on which extensions you have enabled or which page is your homepage, those slugs might actually be perfectly fine.

**Comment by iamdarkle** [comment]
Oh I had no idea, good to know, if is part of the expected behaviour I think there is nothing to do here, I'm closing the issue 🙂
