### ISSUE TITLE
Make the taxonomy terms filter independent of the "Show filter on homepage" option

### ISSUE THREAD

**Issue by iamdarkle** [flamarkt/taxonomies#4]
Currently it is necessary to check the "Show filter on homepage" option to make the taxonomy terms clickable (inside post) and the filter works. I think it would be nice if the filtering was a default and the "Show filter on homepage" option was limited to how it says to show the filter on the homepage. 

I'm currently hiding with CSS the dropdowns of the filters that I don't want to be seen to keep the filtering but it's not the most comfortable option.

**Comment by clarkwinkelmann** [comment]
This single setting is actually supposed to control both the client-side and server-side "preload" for the HTML page, so it's currently all or nothing by design.

I'm not sure it can be enabled by default because of the reserved keywords problem. Using reserved keywords is fine as long as that option is not enabled on a taxonomy.

I don't think it makes sense to have permalinks to terms that way but not from somewhere else. Since there is currently no page listing all taxonomies, there's nowhere else to place a logical link to all terms.

Also having permalinks but no UI control would mean the user can't discard the active filter without manually going back to the index or editing the URL.

I'm not sure I want to refactor it. Renaming to "enable frontend filters" might maybe make more sense based on the actual feature it connects to.

REST API filtering is always possible on all taxonomies.

Ideas on how to refactor the filter system/UI definitely welcome!

**Comment by clarkwinkelmann** [comment]
There are now 2 settings available since version 0.1.7 to control this behavior.

**Comment by iamdarkle** [comment]
I've had a look, I've disabled the option "Show filters on list/directory pages", with that the dropdown has disappeared and I've left only the option "Enable query-string/API filters" in this case the filtering `?taxonomy=` in the URL should work?

I see that the terms are clickable from the discussion, but the filtering doesn't seem to work, in fact if you disable also the option "Enable query-string/API filters" the behaviour is the same clickable but the filter doesn't work.

**Comment by clarkwinkelmann** [comment]
I really didn't test this well, not sure how I missed it.

I have pushed version 0.1.8 where this is hopefully working as intended.

**Comment by iamdarkle** [comment]
Now it seems to work fine clicking through the internal link in the discussion hero, but if you do a full refresh or directly via URL the filter breaks, it doesn't seem to happen with the "Show filters on list/directory pages" option enabled.

Just in case, I'll test some more in case it's my end (some extension doing something weird).

**Comment by iamdarkle** [comment]
I have checked disabling everything, this issue doesn't seem to be related to other extensions.
